import { ApiProperty } from '@nestjs/swagger';

export class Book {
    @ApiProperty({ example: 1, description: 'Autogenerated numeric ID' })
    id: number;

    @ApiProperty({ example: 'Treasure Island' })
    title: string;

    @ApiProperty({ example: 'Robert Louis Stevenson' })
    author: string;

    @ApiProperty({ example: 1883 })
    year: number;
}
