import { ApiProperty } from '@nestjs/swagger';

export class Review {
    @ApiProperty({ example: 1, description: 'Autogenerated numeric ID' })
    id: number;

    @ApiProperty({ example: '1' })
    bookID: number;

    @ApiProperty({ example: '5' })
    rating: number;

    @ApiProperty({ example: "Amazing book!" })
    comment: string;
}
